CREATE DATABASE IF NOT EXISTS apidata;

CREATE USER 'myuser'@'%' IDENTIFIED BY 'userpass';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `apidata`.* TO 'myuser'@'%';

FLUSH PRIVILEGES;